---
name: rpmbuild
on: [push]
jobs:
  build-scl-rpm:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - name: Install required packages
        run: |
          yum install -y rpm-build scl-utils-build scl-utils
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build SRPM package
        run: |
          rpmbuild --define "_topdir `pwd`" -bs ./SPECS/aje-vim82.spec
      - name: Build RPM package
        run: |
          rpmbuild --rebuild --define "_topdir `pwd`" ./SRPMS/*.src.rpm
      - name: Save RPM artefacts
        uses: actions/upload-artifact@v2
        with:
          name: scl-rpm
          path: |
            RPMS/noarch/*.rpm
          retention-days: 10
      - name: Save SRPM artefacts
        uses: actions/upload-artifact@v2
        with:
          name: scl-srpm
          path: |
            SRPMS/*.rpm
          retention-days: 10
  build-vim-rpm:
    runs-on: ubuntu-latest
    container: centos:7
    needs: build-scl-rpm
    steps:
      - name: Install required packages
        run: |
          yum install -y rpm-build scl-utils-build scl-utils rpmdevtools
      - name: Fetch SCL rpm artefacts
        uses: actions/download-artifact@v2
        with:
          name: scl-rpm
      - name: Install SCL packages and clean no longer used rpm files
        run: |
          yum install -y ./*.rpm
          rm -rvf ./*.rpm
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Fetch remote Vim sources
        run: >-
          spectool --define "_topdir `pwd`" -g
          -C SOURCES/ SPECS/aje-vim82-vim.spec
      - name: Build SRPM package
        run: |
          rpmbuild --define "_topdir `pwd`" -bs ./SPECS/aje-vim82-vim.spec
      - name: Install build dependencies
        run: |
          yum-builddep -y ./SRPMS/*.src.rpm
      - name: Build RPM package
        run: |
          rpmbuild --rebuild --define "_topdir `pwd`" ./SRPMS/*.src.rpm
      - name: Save RPM artefacts
        uses: actions/upload-artifact@v2
        with:
          name: vim-rpm
          path: |
            RPMS/x86_64/*.rpm
          retention-days: 10
      - name: Save SRPM artefacts
        uses: actions/upload-artifact@v2
        with:
          name: vim-srpm
          path: |
            SRPMS/*.rpm
          retention-days: 10
  lint-rpm:
    runs-on: ubuntu-latest
    container: centos:7
    needs: build-vim-rpm
    steps:
      - name: Install required packages
        run: |
          yum install -y rpmlint
      - name: Ignore  dir-or-file-in-opt errors
        run: |
          echo 'addFilter("E: dir-or-file-in-opt")' >> /etc/rpmlint/config
          echo 'addFilter("E: non-standard-dir-perm")' >> /etc/rpmlint/config
      - name: Fetch SCL RPM
        uses: actions/download-artifact@v2
        with:
          name: scl-rpm
      - name: Fetch Vim RPM
        uses: actions/download-artifact@v2
        with:
          name: vim-rpm
      - name: Lint all RPM files
        run: |
          rpmlint *.rpm
